[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"
default-run = "aoc-2022"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
gcollections = "1.5.0"
intervallum = "1.4.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
pico-args = "0.5.0"
regex = "1.7.0"
